---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openrmfpro-demo
  region: us-east-1
  version: '1.29'

nodeGroups:
  - name: openrmfpro-demo-ng1-public
    instanceType: m6a.4xlarge
    minSize: 6
    desiredCapacity: 6
    volumeSize: 100
    amiFamily: Bottlerocket
    maxSize: 8
    labels:
      "role": "worker"
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        albIngress: true
cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"
